 # Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e83596ff2b168f5435aeb228533dff91d8d7e56e9fc2e941ac30b81b801d1e4420a710b3ebde0550bd3b6e4540e791f019ac36d5b812c3bd527bd38d29a2d0d1
  facebook_id: <%= ENV["FACEBOOK_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  cloud_name: <%= ENV["CD_CLOUD_NAME"] %>
  api_key: <%= ENV["CD_KEY"] %>
  api_secret: <%= ENV["CD_SECRET"] %>
  enhance_image_tag: true
  static_image_support: false

test:
  secret_key_base: 252e8a1668543605dd421ea06e6560969e97961c908eb7b872daf2cb1be9815214f000e5597a0756373d8c777f6f5c4dddd40d82984404efa07d5dcba87d6d7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_id: <%= ENV["BOOKSTORE_FACEBOOK_ID"] %>
  facebook_secret: <%= ENV["BOOKSTORE_FACEBOOK_SECRET"] %>
  cloud_name: <%= ENV["CD_CLOUD_NAME"] %>
  api_key: <%= ENV["CD_KEY"] %>
  api_secret: <%= ENV["CD_SECRET"] %>
  enhance_image_tag: true
  static_image_support: true
